### ISSUE TITLE
Mini-Task list

### ISSUE THREAD

**Issue by kennethtran93** [kennethtran93/Cookie-AutoDelete#1]
List of items that I plan to work upon soon, at the very least items that I could potentially work on more easily than others.  Just got my desktop linux refreshed after a while, so will need to get my development workflow back up again.

This list is not in order of what I will work on first.

- [x] Update dependencies (long overdue)
  - Released as v3.0.3
- [ ] Automation, test, compiling (Travis CI stuff).
  - notes:  https://github.com/mozilla/sign-addon & https://github.com/mozilla/sign-addon/blob/master/.travis.yml
- [ ] Export of small debugging info for copy-paste into GitHub Issues
  - CAD Version
  - Browser
  - Operating System (?)
  - 'Core' Settings
- [ ] Export of cleanup logs (maybe for debugging assistance?)
- [ ] Better import/export system (for multi-platform)
- [ ] #567 Multiple Expression in one line / reject comma-separated values...
- [x] #539 IP Regex Bug
  - Fixed as of PR #619, released as 3.0.4
- [ ] #523 Chrome Localstorage
- [ ] #521 white/grey from logs
- [ ] #527 Import via text file
- [ ] #429 Export of 'Core' Settings
- [ ] #344 Purge expired cookies regardless of white/grey list (maybe).

**Comment by kennethtran93** [comment]
https://github.com/kennethtran93/Cookie-AutoDelete/tree/dep_updates has the dependencies updated to the more recent versions with working tests and fixed/enhanced configuration files.

**Comment by kennethtran93** [comment]
v3.0.3 released for dependency updates.

**Comment by kennethtran93** [comment]
v3.0.4 released for a bugfix and dependency updates.  Also to have CAD be in Mozilla Firefox's addon recommendation program again.

**Comment by kennethtran93** [comment]
For those following along, the next release will add some numbers into various places.  More of an enhancement than bugfix.

Sneak Peek:  
![future_release_popup](https://user-images.githubusercontent.com/6724477/75604612-633d3400-5a8f-11ea-8ce6-cd782727bbc2.png)

**Comment by kennethtran93** [comment]
Closing as I now have CAD access.  See #595 for future updates.
